// <auto-generated />
using System;
using Customer_RestfulAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customer_RestfulAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerPolicy", b =>
                {
                    b.Property<int>("InsuredListId")
                        .HasColumnType("int");

                    b.Property<int>("PoliciesAsInsuredId")
                        .HasColumnType("int");

                    b.HasKey("InsuredListId", "PoliciesAsInsuredId");

                    b.HasIndex("PoliciesAsInsuredId");

                    b.ToTable("PolicyInsured", (string)null);
                });

            modelBuilder.Entity("Customer_RestfulAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Customer_RestfulAPI.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsurerId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InsurerId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("CustomerPolicy", b =>
                {
                    b.HasOne("Customer_RestfulAPI.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("InsuredListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer_RestfulAPI.Models.Policy", null)
                        .WithMany()
                        .HasForeignKey("PoliciesAsInsuredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Customer_RestfulAPI.Models.Policy", b =>
                {
                    b.HasOne("Customer_RestfulAPI.Models.Customer", "Insurer")
                        .WithMany("PoliciesAsInsurer")
                        .HasForeignKey("InsurerId");

                    b.Navigation("Insurer");
                });

            modelBuilder.Entity("Customer_RestfulAPI.Models.Customer", b =>
                {
                    b.Navigation("PoliciesAsInsurer");
                });
#pragma warning restore 612, 618
        }
    }
}
